# Generated by Django 6.1.1 on 2026-09-20 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(db_index=True, max_length=255)),
                ('pr_number', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('verdict', models.CharField(blank=True, choices=[('block', 'Block'), ('request-changes', 'Request changes'), ('approve-with-conditions', 'Approve with conditions'), ('approve', 'Approve')], max_length=32)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('pr_title', models.CharField(blank=True, max_length=500)),
                ('pr_url', models.URLField(blank=True)),
                ('head_sha', models.CharField(blank=True, max_length=64)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('degraded', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('published', models.BooleanField(default=False)),
                ('trigger', models.CharField(default='api', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('path', models.CharField(max_length=1024)),
                ('line', models.PositiveIntegerField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('category', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.review')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['repo', 'pr_number', '-created_at'], name='reviews_rev_repo_ce26ca_idx'),
        ),
    ]
