# Generated by Django 6.1.1 on 2026-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='suggestion',
            field=models.TextField(blank=True),
        ),
    ]
